name: publish manually

on: workflow_dispatch

jobs:
  publish_android_manually:
    name: Publish Android Manually
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Run pub.dev/inject-credentials@shell
        env:
          CREDENTIALS: ${{ secrets.CREDENTIALS_JSON }}
        run: |
          if [ -z $PUB_CACHE ];then
            PUB_CACHE=~/.pub-cache
          fi
          mkdir -p $PUB_CACHE
          echo $CREDENTIALS > $PUB_CACHE/credentials.json
      - run: flutter --version
      - run: cd alipay_kit_android; flutter pub get
      - run: cd alipay_kit_android; flutter format --dry-run --set-exit-if-changed .
      - run: cd alipay_kit_android; echo "y" | flutter pub publish
      - name: Run pub.dev/update-credentials@shell
        env:
          UPDATE_SECRETS_PAT_TOKEN: ${{ secrets.UPDATE_SECRETS_PAT_TOKEN }}
        run: |
          gh auth login --with-token <<< $UPDATE_SECRETS_PAT_TOKEN
          gh secret set CREDENTIALS_JSON < $PUB_CACHE/credentials.json
